    [env:espidf]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.offset_address = 0x10000
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
build_flags =
    -DOTA_PASSWORD=\"esprccar\"

[env:espidf_ota]
extends = env:espidf
upload_protocol = espota
upload_port = esp-rc-car.local
upload_flags =
    --auth=esprccar

[env:espidf_factory]
extends = env:espidf
build_flags =
    -DFACTORY_BUILD
    -DOTA_PASSWORD=\"esprccar\"

[env:espidf_cdc]
extends = env:espidf
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.cdc.defaults"
upload_flags =
    --before=no_reset
    --after=no_reset

[env:espidf_spi_test]
extends = env:espidf
build_flags =
    -DOTA_PASSWORD=\"esprccar\"
    -DSPI_TEST_ONLY

[env:espidf_step_test]
extends = env:espidf_cdc
build_flags =
    -DOTA_PASSWORD=\"esprccar\"
    -DSTEP_TEST
